
name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag lincolntx/buckstore.orders:latest
          docker login -u ${DOCKERHUBUSER} -p ${DOCKERHUBPASS}
          docker push lincolntx/buckstore.orders:latest
        env:
          DOCKERHUBUSER: ${{secrets.DOCKER_HUB_USER_NAME}}
          DOCKERHUBPASS: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}